name = "WavefieldRecovery"
authors = ["Yijun"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"

[compat]
DrWatson = "2.9.1"
julia = "1.6.7"
